package com.reminder.service.integration;

import org.testng.Assert;
import org.testng.annotations.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 * This class is used to create a Table in HSQLDB database
 */

public class CreateTableTest {

    @Test
    public void testCreateTable() {
        Connection con = null;
        Statement stmt = null;
        int result = 0;
        try {
            Class.forName("org.hsqldb.jdbcDriver");
            con = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/reminderservdb", "sa", "");
            stmt = con.createStatement();
            String create = "CREATE MEMORY TABLE PUBLIC.REMINDER(ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,NAME VARCHAR(50),DESCRIPTION VARCHAR(200),DUE_DATE INTEGER,STATUS VARCHAR(20),CONSTRAINT PKID PRIMARY KEY(ID))" ;
            result = stmt.executeUpdate(create);
        }  catch (Exception e) {
            e.printStackTrace(System.out);
            Assert.assertEquals(result, 1, "Table REMINDER creation is failed!");
        }
    }
}
